version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
    links:
      - "mysql1:database"
  mysql1:
    image: mysql
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: User 
